MyEJB/MyEJB-web/src/main/java/ApplicationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.mycompany.Logic.MyNewSessionBeanRemote;

import javax.ejb.EJB;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;


/**
 *
 * @author RENT
 */
@ManagedBean(name = "applicationController")
@ApplicationScoped
public class ApplicationController {
    @EJB
    private MyNewSessionBeanRemote bean;

    /**
     * Creates a new instance of ApplicationController
     */
    public ApplicationController() {
    }
    
    public String getText(){
        bean.addBook("Tytul ksiazki");
        return "tytul ksiazki wpisany recznie";
    }
    
}

MyEJB/MyEJB-web/src/main/java/pl/controllers/books/AddBookController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.controllers.books;

import com.mycompany.Logic.BookBeanIfc;
import com.mycompany.model.Author;
import com.mycompany.model.Book;
import java.util.ArrayList;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "addBookController")
@RequestScoped
public class AddBookController {

    @EJB
    private BookBeanIfc bookBean;

    private String title;
    private String isbn;
    private int releaseDate;
    private String authors;

    /**
     * Creates a new instance of AddBookController
     */
    public AddBookController() {
    }

    public BookBeanIfc getBookBean() {
        return bookBean;
    }

    public void setBookBean(BookBeanIfc bookBean) {
        this.bookBean = bookBean;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public int getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(int releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getAuthors() {
        return authors;
    }

    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public void save() {
        try {
            Book book = new Book();
            book.setIsbn(isbn);
            book.setReleaseDate(releaseDate);
            book.setTitle(title);
            
            String[] authorsTable = authors.split(",");
            ArrayList<Author> bookAuthors = new ArrayList<>();
            for(String name : authorsTable){
                Author author = new Author();
                author.setName(name);
                
                ArrayList<Book> arrayList = new ArrayList<Book>();
                arrayList.add(book);
                author.setBooks(arrayList);
                bookAuthors.add(author);
            }
            book.setAuthors(bookAuthors);
            bookBean.addBook(book);      
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}

MyEJB/MyEJB-web/src/main/java/pl/controllers/books/BooksTableController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.controllers.books;

import com.mycompany.Logic.BookBeanIfc;
import com.mycompany.Logic.UserBeanIfc;
import com.mycompany.model.Book;
import dtos.BookDto;
import javax.ejb.EJB;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import org.modelmapper.ModelMapper;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "booksTableController")
@RequestScoped
public class BooksTableController {

    @EJB
    private BookBeanIfc bbi;
    @EJB
    private UserBeanIfc ubi;
    
    public BooksTableController() {
    }

    public List<BookDto> getList() {
        List<Book> books = bbi.getBooks();
        List<BookDto> collect;
        collect = books.stream().map(this::map).collect(Collectors.toList());

        return collect;
    }

    private BookDto map(Book b) {
        ModelMapper mapper = new ModelMapper();
        BookDto map = mapper.map(b, BookDto.class);
        return map;
    }

    private void collect(Collector<Object, ?, List<Object>> toList) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String rentBook(Long id) {
        ubi.rentBook(1L, id); //user id = 1 bo mam tylko 1 usera
        return "";
    }
}

MyEJB/MyEJB-web/src/main/webapp/addbook.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:body>
        <ui:composition template = "index.xhtml">

            <ui:define name = "content">
                <h:form>
                    <div class="row">
                        <div class="col-md-3">
                            tytul
                        </div>
                        <div class="col-md-3">
                            <h:inputText value="#{addBookController.title}"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            ISBN
                        </div>
                        <div class="col-md-3">
                            <h:inputText value="#{addBookController.isbn}"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            data wydania
                        </div>
                        <div class="col-md-3">
                            <h:inputText value="#{addBookController.releaseDate}"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            autorzy (po przecinku)
                        </div>
                        <div class="col-md-3">
                            <h:inputText value="#{addBookController.authors}"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            zapisz
                        </div>
                        <div class="col-md-3">
                            <h:commandButton action="#{addBookController.save}" value="Zapisz"/>
                        </div>
                    </div>
                </h:form>
            </ui:define>

        </ui:composition>

    </h:body>
</html>

MyEJB/MyEJB-web/src/main/webapp/authors.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>

MyEJB/MyEJB-web/src/main/webapp/books.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:body>
        <ui:composition template = "index.xhtml">

            <ui:define name = "content">
                BOOKS
            </ui:define>

        </ui:composition>

    </h:body>
</html>

MyEJB/MyEJB-web/src/main/webapp/contents.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      >
    <body>
        <ui:composition>
            <h:dataTable styleClass="table table-striped"
                         value="#{booksTableController.list}" var="book">
                <h:column>
                    <f:facet name="header">Tytul</f:facet>
                            #{book.bookTitle}
                </h:column>
                <h:column>
                    <f:facet name="header">Data Wydania</f:facet>
                            #{book.bookReleaseDate}
                </h:column>
                <h:column>
                    <f:facet name="header">Autorzy</f:facet>
                    <ui:repeat value="#{book.authors}" var="autor">
                        <!--<h:outputText value="#{autor.authorName}" />-->
                    </ui:repeat>
                </h:column>                

            </h:dataTable>

        </ui:composition>
    </body>
</html>

MyEJB/MyEJB-web/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:f = "http://java.sun.com/jsf/core"
      xmlns:h = "http://java.sun.com/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">
        
    <h:head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <link rel="icon" href="../../favicon.ico"/>

        <title>Wynajem ksiazki Lukasz Migodzinski</title>

        <!-- Bootstrap core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet"/>

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>

        <!-- Custom styles for this template -->
        <link href="css/starter-template.css" rel="stylesheet"/>
    </h:head>

    <h:body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Biblioteka</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.xhtml">Home</a></li>
                        <li><h:outputLink value="users.xhtml">Uzytkownicy</h:outputLink></li>
                        <li><h:outputLink value="books.xhtml">Ksiazki</h:outputLink></li>
                        <li><h:outputLink value="addbook.xhtml">Dodaj Ksiazki</h:outputLink></li>
                        <li><h:outputLink value="authors.xhtml">Autorzy</h:outputLink></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="starter-template" style="padding-top: 50px">
                <ui:insert name="content" >
                    <ui:include src="contents.xhtml"/>
                </ui:insert>
            </div>
        </div> <!-- /.container -->




        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script type="text/javascript" src="js/ie10-viewport-bug-workaround.js"></script>
    </h:body>
</html>

MyEJB/MyEJB-web/src/main/webapp/users.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>